# Use a Python base image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app code to the working directory
COPY generate_data.py .

# Set the entrypoint to run the Flask app
ENTRYPOINT ["python", "generate_data.py"]